service: cpas-jwt-token-verifier

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

functions:
  cpas-jwt-token-verifier:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'